Correct style to conform to linters
coderacheal/Trial-project pull request #1
Opened 2022-12-13 22:05 UTC by coderacheal

Made correction to the different style sheets so they conform to the linter specification

2022-12-13 22:59 UTC, coderacheal reviewed
Hi @coderacheal 

Nice work!
However, there are a few things to work on to make your code better

![a-little-bit-more](https://user-images.githubusercontent.com/97846040/207462772-f39cba43-cf08-4bdd-b358-7b2f3cb1ec42.gif)

# Highlights 💯 
-Professional-looking readme file. ✔️
-No linter errors ✔️

 # Required changes ♻️ 
Please check the comments under the code and make the necessary changes

# Optional Changes
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-12-13 22:59 UTC, coderacheal commented on index.html
> +            </button>
Please next time, you can use a list to place these items much easier

2022-12-13 22:59 UTC, coderacheal commented on index.html
> +            <div id="comment-count-and-sorting-div">
Please use **section** instead of **div**. This makes your html more semantic and browser friendly

2022-12-13 22:59 UTC, coderacheal commented on index.html
> +            <div id="comment-session">
Please use **section** instead of **div**. This makes your html more semantic and browser friendly

2022-12-13 22:59 UTC, coderacheal commented on index.html
> +        <div id="small-player-column">
Please use **section** instead of **div**. This makes your html more semantic and browser friendly

2022-12-13 22:59 UTC, coderacheal commented on index.html
> +            <div id="mini-player">
Please use **section** instead of **div**. This makes your html more semantic and browser friendly

2022-12-13 22:59 UTC, coderacheal commented on styles/general.css
> -    /* background-color: black; */
Please do no leave unused code in your source code

2022-12-13 22:59 UTC, coderacheal commented on index.html
> +            <input id="search-bar" type="text" placeholder="Search">
Please always add a name attribute to your input element. It makes data collection easier and seamless

2022-12-13 22:59 UTC, coderacheal commented on index.html
> +                    <button id="more">&#8230;</button>
An alternative for easy placement would be ul/li

2022-12-13 23:20 UTC, Owusu-Desmond commented on index.html
> +            <div id="comment-count-and-sorting-div">
- [ ] Hi @coderacheal, Good job :+1: using inline comments but I suggest it would be better to state your comments politely, as suggestions instead of orders. For example:

* This is a polite suggestion: *"I think it would be better to use semantic tags to ..."*

2022-12-13 23:21 UTC, Owusu-Desmond commented on index.html
> +            <div id="comment-session">
- [ ] Hi @coderacheal, Good job :+1: using inline comments but I suggest it would be better to state your comments politely, as suggestions instead of orders. For example:

* This is a polite suggestion: *"I think it would be better to use semantic tags to ..."*

2022-12-13 23:21 UTC, Owusu-Desmond commented on index.html
> +        <div id="small-player-column">
- [ ] Hi @coderacheal, Good job :+1: using inline comments but I suggest it would be better to state your comments politely, as suggestions instead of orders. For example:

* This is a polite suggestion: *"I think it would be better to use semantic tags to ..."*

2022-12-13 23:21 UTC, Owusu-Desmond commented on index.html
> +            <div id="mini-player">
- [ ] Hi @coderacheal, Good job :+1: using inline comments but I suggest it would be better to state your comments politely, as suggestions instead of orders. For example:

* This is a polite suggestion: *"I think it would be better to use semantic tags to ..."*

2022-12-13 23:25 UTC, Owusu-Desmond commented on index.html
> +                    <button id="more">&#8230;</button>
- [ ] Hi @coderacheal, Good job :+1: using inline comments but I suggest it would be better to state your comments politely, as suggestions instead of orders, and state the reason for your suggestion. For example:

* This is a polite suggestion: *"Please I suggest it would be better to use `ul` and `li` elements to list these buttons for better placement :smile: ..."*

2022-12-13 23:29 UTC, Owusu-Desmond commented on styles/general.css
> -    /* background-color: black; */
Hi @coderacheal, please since the background of this inline commented code is light red, this means it is not available in the project code anymore so next time you should not comment on such code.

2022-12-13 23:30 UTC, Owusu-Desmond commented on index.html
> +            </button>
- [ ] Hi @coderacheal, Good job :+1: using inline comments but I suggest it would be better to state your comments politely, as suggestions instead of orders, and state the reason for your suggestion. For example:

* This is a polite suggestion: *"Please I suggest it would be better to use `ul` and `li` elements to list these buttons for better placement :smile: ..."*

2022-12-13 23:34 UTC, Owusu-Desmond requested changes
Hi @coderacheal , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good to use inline comments ✅
📌 Good to use the changes required feature on github ✅

## Required Changes ♻️
_Check the comments under your review._

## Optional suggestions

- [ ] Please you can use a couple of emojis and/or gifs in the review. They make the code review more human-friendly 👽🤖.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 00:37 UTC, coderacheal reviewed
Hi @coderacheal

Nice work!
However, there are a few things to work on to make your code better

![a-little-bit-more](https://user-images.githubusercontent.com/97846040/207475646-929b0d51-66a7-401f-8a58-fde44b6f51eb.gif)


Highlights 💯
-Professional-looking readme file. ✔️
-No linter errors ✔️

Required changes ♻️
Please check the comments under the code and make the necessary changes

Optional Changes
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-12-14 00:37 UTC, coderacheal commented on index.html
> +            </button>
Please I suggest you use ul & li tags as they make for better placement

2022-12-14 00:37 UTC, coderacheal commented on index.html
> +                    <button id="more">&#8230;</button>
Please I suggest you use ul & li tags as they make for better placement

2022-12-14 00:37 UTC, coderacheal commented on index.html
> +            <div id="comment-count-and-sorting-div">
I think it would be better to use semantic tags such as **section** in place of **div**. This makes your html more semantic and browser friendly

2022-12-14 00:37 UTC, coderacheal commented on index.html
> +            <div id="comment-session">
I think it would be better to use semantic tags such as section in place of div. This makes your html more semantic and browser friendly

2022-12-14 00:37 UTC, coderacheal commented on index.html
> +        <div id="small-player-column">
I think it would be better to use semantic tags such as section in place of div. This makes your html more semantic and browser friendly

2022-12-14 00:37 UTC, coderacheal commented on index.html
> +            <div id="mini-player">
I think it would be better to use semantic tags such as section in place of div. This makes your html more semantic and browser friendly

2022-12-14 00:50 UTC, Olamarx approved these changes
Hi @coderacheal,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>
## Highlights
- GitHub review feature ✔️ 
- Inline comments ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 06:44 UTC, merged